version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      include: scope
      prefix: ci
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: monthly
    commit-message:
      include: scope
      prefix: deps
      prefix-development: chore
    groups:
      terraform:
        patterns:
          - github.com/hashicorp/*
      test:
        patterns:
          - github.com/jarcoal/httpmock
          - github.com/stretchr/testify
