version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "monthly"
