linters:
  enable:
    - gofmt
    - revive
    - gocyclo
    - misspell
    - whitespace
    - goimports
    - gofmt
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/articulate/terraform-provider-ohdear
