version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - err113
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocyclo
    - gosec
    - gosmopolitan
    - lll
    - loggercheck
    - makezero
    - misspell
    - modernize
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nonamedreturns
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - spancheck
    - testifylint
    - thelper
    - tparallel
    - usetesting
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - perfsprint
    - rowserrcheck
    - sqlclosecheck
  settings:
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^spew\.(ConfigState\.)?Dump$
      analyze-types: true
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
          - funlen
          - lll
          - wrapcheck
        path: _test\.go
      - linters:
          - funlen
          - gochecknoinits
          - nestif
        path: internal/.+\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
