linters:
  presets:
    - bugs
    - error
    - performance
  enable:
    - gofmt
    - gofumpt
    - revive
    - gocyclo
    - misspell
    - whitespace
    - goimports
    - gosec
    - lll
  disable:
    - scopelint
    - rowserrcheck
    - sqlclosecheck
    - maligned

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errorlint
        - goerr113
        - wrapcheck

linters-settings:
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/articulate/terraform-provider-ohdear
