sudo: required
language: go
go:
- 1.10.x
- tip
install:
- make deps
- make testacc
script:
- make build
branches:
  only: master
env:
  global:
    secure: RiqF5IczysVug1VJACSvvoMRPsXuvBfBCvQx+KqUILsaYNgqdB5vtsgFXD3ZF8IbKTZm76MoSpUVoEVKjzMAa/jEZ+9OEsRQbKH2nepvAaZzoacP2bBNArkU0R6gMuCUK/idneK4onlUNKpgST99FXoRj/V86AWoJE9ZDkOD9h2e0X8Gak+3uVTi5TUzyKXppiyBewxTmVrYMIP+9vm9gcltpqxFO56ACsqeT8ZXoZRsviAa6aKyHm+kaghzOR62toO5UQw1Sr+EviBl/TL7fYFOAHa3Fo22ieW6Gd3tRU73jni/25NxTDi0oucd1VmQJaasN4Io7W5HBwef4LCKGAEPY+MZ5dm99DDsiTO6fCDTt3gKcotRQ4cm9O6oaXDr4VOS638B0uQeWndUiohpJijzupTjYsyxYyei6ZK4fTxkzrHWD/CudV7YOeHmKlDW67Uee4bEWOozEwnrlCWvJyt05c7qO6yleENhIVqeXPMPLmx7ZONvRHGWReBwhOOnHTwBe4DSJff/TtHaV/7LLeweB2QE6eUew1gpf0W0EIOFBiLKcyigyHUtzzFj7gQkJYKkI0O/ySCnyuV+v4CD5kzVbox5Keh14P59vTL0vK7bJMh8hATd0U2kILFefOmR17fqu4KPC6Dt02GyJ/hPKQqg8c7lWGIec6nqZUJnUiA=
