[[constraint]]
  branch = "master"
  name = "github.com/articulate/ohdear-sdk"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.10"

[prune]
  go-tests = true
  unused-packages = true
