name: Test

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - run: go build -v .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - uses: golangci/golangci-lint-action@v3

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        terraform:
          - '1.0.11'
          - '1.1.9'
          - '1.2.9'
          - '1.3.6'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - run: make testacc
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
          OHDEAR_TOKEN: ${{ secrets.OHDEAR_TOKEN }}
          OHDEAR_TEAM_ID: 6944
